# Generated by Django 3.1.4 on 2021-12-29 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='', verbose_name='Product Image')),
                ('product_name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('product_price', models.IntegerField(verbose_name='Product Price')),
                ('on_sale', models.BooleanField(default=False, verbose_name='on sale')),
                ('price_sale', models.IntegerField(verbose_name='Price Sale')),
                ('related_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.category', verbose_name='Related Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
